services:
  db:
    image: mysql:latest
    container_name: "web-shop"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123  # use your own password
      MYSQL_DATABASE: webshop  # name of the database
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
volumes:
  db_data: